class Controller (object):
	"This is the controller for the Algorithm Visuialization module.

	It controls which alg is run, how it is run and the interface of the
	algorithm object and the final GUI
	
	Attributes:
	visualizer: the algorithm visualization object.
	algFactory: the algorithm factory ojects
	algInsance: an instance of a paticular algorithm (generated by 
		algFactory) 
	"
	
	def __init__ (self, guiType = 'default'):
		"""
		Return an instance of the Controller for the AlgVis Module
		"""
		this.visualizer = new Visualizer(guiType)
		this.algFactory = new AlgFactory()
		this.algInstance = None
	
	def start(self, algName = None, algInput = None):
		"""
		Starts a visualization of a paticular algorithm.
		"""
		#if algName == None:
		#	#Prompt the visualizer to ask for an alg name and alg input.
		#	#this.visualizer.
			
		None
		
	
	